#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Public-repo audit. Runs the same checks the CI maintainers and PR reviewers
# do by hand: every commit must be authored + committed by a real human; no
# AI-tinted language anywhere in the source tree or commit messages; SPDX
# headers on every .cpp/.hpp/.c/.h/.py/.sh outside third_party; .gitignore
# must not name local-only files (which would leak their existence); local
# files (e.g. CLAUDE.md) must not be tracked.
#
# Exits non-zero on the first failure; suitable for a release-gate hook.

set -uo pipefail
cd "$(git rev-parse --show-toplevel)"

fail() { echo "AUDIT FAIL: $*" >&2; exit 1; }
ok()   { echo "  ok: $*"; }

echo "fidelis public-repo audit"
echo

# 1. Author + committer identity must be one human.
echo "AUDIT 1: commit identity"
authors=$(git log --format='%an <%ae>' | sort -u | wc -l)
committers=$(git log --format='%cn <%ce>' | sort -u | wc -l)
[ "$authors"    -le 1 ] || fail "$authors distinct authors in history"
[ "$committers" -le 1 ] || fail "$committers distinct committers in history"
ok "authors=$authors committers=$committers"

# 2. No AI-tells in any commit message.
echo "AUDIT 2: commit messages"
if git log --format='%B' | grep -qiE 'claude|anthropic|co-authored|as an AI|language model|generated by AI'; then
  fail "AI-tinted language in a commit message"
fi
ok "all commit messages clean"

# 3. No AI-tells in any tracked file (third_party allowed; that's vendored).
echo "AUDIT 3: tracked tree"
if git grep -qniIE 'claude|anthropic|as an AI|language model|co-authored-by' -- . ':!third_party'; then
  git grep -niIE 'claude|anthropic|as an AI|language model|co-authored-by' -- . ':!third_party'
  fail "AI-tinted language in a tracked file"
fi
ok "tracked tree clean"

# 4. SPDX header on every source file outside third_party.
echo "AUDIT 4: SPDX header coverage"
missing=0
for f in $(git ls-files | grep -E '\.(cpp|hpp|c|h|py|sh)$' | grep -v '^third_party/'); do
  if ! head -3 "$f" | grep -q 'SPDX-License-Identifier'; then
    echo "  MISSING: $f"
    missing=$((missing+1))
  fi
done
[ "$missing" -eq 0 ] || fail "$missing files lack an SPDX header"
ok "every applicable source file declares SPDX"

# 5. .gitignore must not name local-only files (the file itself is tracked
#    so listing those names would leak that they exist).
echo "AUDIT 5: .gitignore hygiene"
if grep -qE 'CLAUDE|\.claude' .gitignore 2>/dev/null; then
  fail ".gitignore names a local-only file (use .git/info/exclude instead)"
fi
ok ".gitignore does not leak local-only filenames"

# 6. Local-only files must not be tracked.
echo "AUDIT 6: local-only files not tracked"
if git ls-files | grep -qiE '^CLAUDE\.md|^\.claude/'; then
  git ls-files | grep -iE '^CLAUDE\.md|^\.claude/'
  fail "local-only file tracked in repo"
fi
ok "no local-only files in the tracked tree"

echo
echo "AUDIT PASSED — repo is safe to push."
